"""Compatibility re-export for the standalone Ophanix Tool Gateway SDK."""

from __future__ import annotations

from ophanix_tool_gateway.sdk import (
    AsyncGatewayHttpClient,
    AsyncOphanixToolGatewayClient,
    AsyncTokenProvider,
    AuthorizationChallenge,
    AuthorizationStatus,
    EnvironmentTokenProvider,
    GatewayCompatibility,
    OphanixToolGatewayClient,
    SDK_VERSION,
    StaticTokenProvider,
    SyncGatewayHttpClient,
    TelemetryEvent,
    TelemetryEventHook,
    TelemetryEventName,
    TokenProvider,
    ToolAuthenticationError,
    ToolAuthorizationRequired,
    ToolCallResult,
    ToolDefinition,
    ToolDeniedError,
    ToolGatewayClientConfig,
    ToolGatewayClientOptions,
    ToolGatewayError,
    ToolGatewayValidationError,
)

__all__ = [
    "AsyncGatewayHttpClient",
    "AsyncOphanixToolGatewayClient",
    "AsyncTokenProvider",
    "AuthorizationChallenge",
    "AuthorizationStatus",
    "EnvironmentTokenProvider",
    "GatewayCompatibility",
    "OphanixToolGatewayClient",
    "SDK_VERSION",
    "StaticTokenProvider",
    "SyncGatewayHttpClient",
    "TelemetryEvent",
    "TelemetryEventHook",
    "TelemetryEventName",
    "TokenProvider",
    "ToolAuthenticationError",
    "ToolAuthorizationRequired",
    "ToolCallResult",
    "ToolDefinition",
    "ToolDeniedError",
    "ToolGatewayClientConfig",
    "ToolGatewayClientOptions",
    "ToolGatewayError",
    "ToolGatewayValidationError",
]
